# Site settings
title: Jonathan Buys
logo: /images/jb_logo.png
description: Technology, Design, and Culture
baseurl: "" # the subpath of your site, e.g. /blog
url: https://jonathanbuys.com # the base hostname & protocol for your site
permalink: /:title/

# Main header
header:
  text_shadow: 0 0 20px rgba(28, 47, 53, .8) # CSS text-shadow

# Navigation
navigation:
  - slug: /
    label: Home
  - slug: /microblog
    label: Tweet
  - slug: /about
    label: About
  - slug: /contact
    label: Contact
  - slug: /archive/
    label: Archive
  - slug: /100books
    label: Reading
    
# Services (all are optional)
# analytics: # Google Analytics tracking ID
# disqus: jasper-theme    # Disqus shortname
# facebook_l10n: en_US    # Your locale (en_US, fr_FR, etc.)
twitter: ibuys    # Website's Twitter username (without the '@')

# Build settings
exclude: [CNAME, Gemfile, Gemfile.lock]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown

# Plugins
gems: [jekyll-paginate]
paginate: 10 # Post excerpts by page
paginate_path: "/page/:num" # Default was "/page:num/"

collections:
  microblog:
    output: true
    permalink: /microblog/:year/:month/:slug/
