# Site settings
title: jb…
email: desk@jonathanbuys.com
description: > # this means to ignore newlines until "baseurl:"
  Step into the arena. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonathanbuys.com" # the base hostname & protocol for your site
twitter_username: ibuys
github_username:  ibuys

# Build settings
markdown: kramdown
paginate: 5
plugins: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown

paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"
permalink: /:title/
