# Site settings
title: jb…
email: desk@jonathanbuys.com
description: > # this means to ignore newlines until "baseurl:"
  Step into the arena. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jonathanbuys.com" # the base hostname & protocol for your site
twitter_username: ibuys
github_username:  ibuys

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown

plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

inter_post_navigation: false
highlightjs_theme: "monokai-sublime"
permalink: /:title/

collections:
  microblog:
    output: true
    permalink: /microblog/:year/:month/:slug/
